import { AdminShell } from '@/components/shell'
import { Card } from '@/components/ui'
import { MetricCard } from '@/components/product'
import { requireAdmin } from '@/lib/admin-auth'
import { adminGrowthReferralData } from '@/lib/growth-associate-referrals'
import Link from 'next/link'

export const dynamic = 'force-dynamic'
const money = (value: number) => `₦${Number(value || 0).toLocaleString('en-NG')}`
export default async function GrowthAssociatesAdmin({ searchParams }: { searchParams?: Promise<{ month?: string }> }) {
  await requireAdmin()
  const params = await searchParams
  const data = await adminGrowthReferralData(params?.month)
  const performance = new Map(data.performance.map((item: any) => [item.partner_id,item]))
  const totalCommission = data.performance.reduce((sum: number,item: any)=>sum+Number(item.commission_amount_ngn),0)
  return <AdminShell title="Growth Associates"><div className="page-grid"><div className="metric-grid"><MetricCard label="Total Associates" value={String(data.partners.length)} note="Existing biodata reused"/><MetricCard label="Active Associates" value={String(data.partners.filter((p:any)=>p.status==='ACTIVE').length)} note="Eligible for attribution"/><MetricCard label="Successful Referrals" value={String(data.performance.reduce((s:number,p:any)=>s+Number(p.successful_referrals),0))} note={data.month}/><MetricCard label="Commission" value={money(totalCommission)} note="Calculated, not automatically paid"/></div>
    <Card><form className="card-actions"><label>Month <input type="month" name="month" defaultValue={data.month.slice(0,7)}/></label><button className="btn btn-primary">Apply</button></form></Card>
    <Card><h2>Associate performance</h2><div className="responsive-table"><table><thead><tr><th>Associate</th><th>Status</th><th>Referral ID</th><th>Target</th><th>Referrals</th><th>Progress</th><th>L1 / L2</th><th>Actions</th></tr></thead><tbody>{data.partners.map((partner:any)=>{const item:any=performance.get(partner.id)||{}; return <tr key={partner.id}><td>{partner.full_name}<small>{partner.email}</small></td><td>{partner.status}</td><td>{partner.referral_codes?.[0]?.code||partner.partner_id}</td><td>30</td><td>{item.successful_referrals||0}</td><td>{Math.min(Math.round(Number(item.successful_referrals||0)/30*100),100)}%</td><td>{money(item.l1_commission_ngn)} / {money(item.l2_commission_ngn)}</td><td><div className="card-actions"><Link className="btn btn-primary" href={`/admin/growth-associates/${partner.id}`}>View profile</Link><a className="btn btn-secondary" href={partner.referral_codes?.[0]?.referral_url||'#'}>Referral link</a><a className="btn btn-secondary" href={`/associate/${partner.partner_id}`}>Portal</a></div></td></tr>})}</tbody></table></div></Card>
    <Card><h2>Leaderboard</h2><div className="responsive-table"><table><thead><tr><th>Rank</th><th>Associate</th><th>Referrals</th><th>Target</th><th>Commissionable</th><th>Commission</th></tr></thead><tbody>{data.performance.map((item:any,index:number)=>{const partner:any=data.partners.find((p:any)=>p.id===item.partner_id);return <tr key={item.id}><td>#{index+1}</td><td>{partner?.full_name||'Associate'}</td><td>{item.successful_referrals}</td><td>30</td><td>{item.commissionable_referrals}</td><td>{money(item.commission_amount_ngn)}</td></tr>})}</tbody></table></div></Card>
    <Card><h2>Referral records</h2><div className="responsive-table"><table><thead><tr><th>Date</th><th>Associate</th><th>Code</th><th>Payment</th><th>Course</th><th>Status</th><th>Commission</th><th>Invalidate</th></tr></thead><tbody>{data.conversions.map((item:any)=><tr key={item.id}><td>{new Date(item.successful_at).toLocaleDateString()}</td><td>{item.partners?.full_name}</td><td>{item.referral_codes?.code}</td><td>{item.payments?.paystack_reference}</td><td>{item.payments?.payment_items?.map((x:any)=>x.programmes?.name).filter(Boolean).join(', ')}</td><td>{item.status}</td><td>{money(item.commission_amount_ngn)}</td><td>{item.status==='VALID'?<form action="/api/admin/growth-associates" method="post" className="compact-form"><input type="hidden" name="action" value="invalidate_referral"/><input type="hidden" name="id" value={item.id}/><input name="reason" required placeholder="Reason"/><button className="btn btn-secondary">Invalidate</button></form>:'—'}</td></tr>)}</tbody></table></div></Card>
    <Card><h2>Commission controls</h2>{data.performance.filter((item:any)=>item.commission_amount_ngn>0).map((item:any)=>{const partner:any=data.partners.find((p:any)=>p.id===item.partner_id);return <form action="/api/admin/growth-associates" method="post" className="payout-form" key={item.id}><input type="hidden" name="action" value="record_payout"/><input type="hidden" name="performanceId" value={item.id}/><input type="hidden" name="partnerId" value={item.partner_id}/><strong>{partner?.full_name} · {money(item.commission_amount_ngn)}</strong><input type="number" name="amount" value={item.commission_amount_ngn} readOnly/><select name="status" defaultValue={item.status==='CALCULATED'?'PENDING':item.status}><option>PENDING</option><option>APPROVED</option><option>PAID</option></select><input name="reference" required placeholder="Payout reference"/><input name="paymentMethod" placeholder="Payment method"/><input name="reason" placeholder="Admin notes"/><button className="btn btn-primary">Save</button></form>})}</Card>
  </div></AdminShell>
}
