import Link from 'next/link'
import { notFound } from 'next/navigation'
import { AdminShell } from '@/components/shell'
import { Card } from '@/components/ui'
import { requireAdmin } from '@/lib/admin-auth'
import { createSupabaseAdminClient } from '@/lib/supabase/admin'

const money = (value: number) => `₦${Number(value || 0).toLocaleString('en-NG')}`
export default async function AssociateProfile({ params }: { params: Promise<{ id: string }> }) {
  await requireAdmin()
  const { id } = await params
  const db = createSupabaseAdminClient()
  const [partnerResult, partnersResult, performanceResult, conversionsResult, payoutsResult] = await Promise.all([
    db.from('partners').select('*,referral_codes(*)').eq('id', id).maybeSingle(), db.from('partners').select('id,full_name,partner_id').neq('id',id).order('full_name'), db.from('associate_monthly_performance').select('*').eq('partner_id',id).order('month_start',{ascending:false}), db.from('referral_conversions').select('*,payments(paystack_reference,amount_ngn)').eq('partner_id',id).order('successful_at',{ascending:false}), db.from('payout_requests').select('*').eq('partner_id',id).order('created_at',{ascending:false})
  ])
  const p:any=partnerResult.data; if(!p) notFound()
  const referral=p.referral_codes?.find((x:any)=>x.active)||p.referral_codes?.[0]
  return <AdminShell title="Growth Associate Profile"><div className="page-grid"><Card><div className="card-actions"><Link className="btn btn-secondary" href="/admin/growth-associates">Back</Link><a className="btn btn-primary" href={referral?.referral_url||'#'}>Open referral link</a><a className="btn btn-primary" href={`/associate/${p.partner_id}`}>Open portal</a></div><h2>{p.full_name}</h2><p>{p.email} · {p.whatsapp||'No phone'}</p><p><strong>Referral ID:</strong> {referral?.code||p.partner_id}</p><p><strong>Institution:</strong> {p.institution||'—'} · <strong>Field:</strong> {p.field_of_study||'—'}</p><p><strong>NYSC:</strong> {p.nysc_information||'—'} · <strong>Location:</strong> {p.location||'—'}</p></Card><Card><h2>Level 2 hierarchy</h2><form action="/api/admin/growth-associates" method="post" className="card-actions"><input type="hidden" name="action" value="assign_sponsor"/><input type="hidden" name="id" value={p.id}/><input type="hidden" name="returnTo" value={`/admin/growth-associates/${p.id}`}/><select name="sponsorPartnerId" defaultValue={p.sponsor_partner_id||''}><option value="">No sponsor</option>{(partnersResult.data||[]).map((x:any)=><option value={x.id} key={x.id}>{x.full_name} ({x.partner_id})</option>)}</select><input name="reason" placeholder="Reason / note"/><button className="btn btn-primary">Save sponsor</button></form></Card><Card><h2>Monthly performance</h2><div className="responsive-table"><table><thead><tr><th>Month</th><th>Direct</th><th>L2</th><th>L1</th><th>L2 commission</th><th>Total</th><th>Status</th></tr></thead><tbody>{(performanceResult.data||[]).map((x:any)=><tr key={x.id}><td>{x.month_start}</td><td>{x.l1_referrals??x.successful_referrals}</td><td>{x.l2_referrals??0}</td><td>{money(x.l1_commission_ngn)}</td><td>{money(x.l2_commission_ngn)}</td><td>{money(x.commission_amount_ngn)}</td><td>{x.status}</td></tr>)}</tbody></table></div></Card><Card><h2>Referrals ({conversionsResult.data?.length||0})</h2><div className="responsive-table"><table><thead><tr><th>Date</th><th>Payment</th><th>Amount</th><th>Status</th><th>L1</th></tr></thead><tbody>{(conversionsResult.data||[]).map((x:any)=><tr key={x.id}><td>{new Date(x.successful_at).toLocaleDateString()}</td><td>{x.payments?.paystack_reference}</td><td>{money(x.payments?.amount_ngn)}</td><td>{x.status}</td><td>{money(x.commission_amount_ngn)}</td></tr>)}</tbody></table></div></Card><Card><h2>Payout history</h2>{(payoutsResult.data||[]).map((x:any)=><p key={x.id}>{x.created_at?.slice(0,10)} · {money(x.approved_amount_ngn||x.requested_amount_ngn)} · {x.status} · {x.reference||'—'}</p>)}</Card></div></AdminShell>
}
