import Link from 'next/link'
import { notFound } from 'next/navigation'
import { AdminShell } from '@/components/shell'
import { Card } from '@/components/ui'
import { ReferralLinkActions } from '@/components/referral-link-actions'
import { requireAdmin } from '@/lib/admin-auth'
import { createSupabaseAdminClient } from '@/lib/supabase/admin'
import { getGrowthAssociatePortalUrl, getGrowthAssociateReferralUrl } from '@/lib/growth-associate-urls'

const money = (value: number) => `₦${Number(value || 0).toLocaleString('en-NG')}`
const field = (value: unknown) => String(value || '')
export const dynamic = 'force-dynamic'

export default async function AssociateProfile({ params }: { params: Promise<{ id: string }> }) {
  await requireAdmin()
  const { id } = await params
  const db = createSupabaseAdminClient()
  const [partnerResult, partnersResult, performanceResult, conversionsResult, payoutsResult, interviewsResult, commissionsResult] = await Promise.all([
    db.from('partners').select('*,referral_codes(*)').eq('id', id).maybeSingle(),
    db.from('partners').select('id,full_name,partner_id').neq('id', id).order('full_name'),
    db.from('associate_monthly_performance').select('*').eq('partner_id', id).order('month_start', { ascending: false }),
    db.from('referral_conversions').select('*,payments(paystack_reference,amount_ngn,payment_items(programmes(name)))').eq('partner_id', id).order('successful_at', { ascending: false }),
    db.from('payout_requests').select('*').eq('partner_id', id).order('created_at', { ascending: false }),
    db.from('associate_interviews').select('*').eq('partner_id', id).order('created_at', { ascending: false }),
    db.from('commissions').select('*').eq('partner_id', id).order('created_at', { ascending: false }),
  ])
  const p: any = partnerResult.data
  if (!p) notFound()
  const referral = p.referral_codes?.find((x: any) => x.active) || p.referral_codes?.[0]
  const referralUrl = referral ? getGrowthAssociateReferralUrl(referral.code) : ''
  const portalUrl = getGrowthAssociatePortalUrl(p.partner_id)
  const current: any = performanceResult.data?.[0] || {}
  const paid = (commissionsResult.data || []).filter((x: any) => x.status === 'PAID').reduce((s: number, x: any) => s + Number(x.amount_ngn || 0), 0)
  const pending = (commissionsResult.data || []).filter((x: any) => ['PENDING', 'APPROVED'].includes(x.status)).reduce((s: number, x: any) => s + Number(x.amount_ngn || 0), 0)
  return <AdminShell title="Growth Associate Profile"><div className="page-grid">
    <Card><div className="card-actions"><Link className="btn btn-secondary" href="/admin/growth-associates">Back</Link>{referralUrl ? <a className="btn btn-primary" href={referralUrl} target="_blank">Open referral link</a> : null}<a className="btn btn-primary" href={portalUrl} target="_blank">Open secure portal</a><form action="/api/admin/growth-associates" method="post"><input type="hidden" name="action" value="invite_portal"/><input type="hidden" name="id" value={p.id}/><input type="hidden" name="returnTo" value={`/admin/growth-associates/${p.id}`}/><button className="btn btn-secondary">{p.user_id ? 'Portal access linked' : 'Send portal invitation'}</button></form><form action="/api/admin/growth-associates" method="post"><input type="hidden" name="action" value="sync_legacy_hr"/><input type="hidden" name="id" value={p.id}/><input type="hidden" name="returnTo" value={`/admin/growth-associates/${p.id}`}/><button className="btn btn-secondary">Sync historical HR data</button></form></div><h2>{p.full_name}</h2><p>{p.email} · {p.whatsapp || 'No phone'} · {p.recruitment_status}</p><p><strong>Growth ID:</strong> {p.partner_id} · <strong>Referral ID:</strong> {referral?.code || 'Not assigned'}</p>{referralUrl ? <><code className="referral-url">{referralUrl}</code><ReferralLinkActions url={referralUrl}/></> : null}<p><strong>Portal:</strong> <a href={portalUrl}>{portalUrl}</a></p></Card>
    <div className="metric-grid"><Card><p className="eyebrow">Monthly referrals</p><strong className="metric-value">{current.successful_referrals || 0} / {current.target || 30}</strong></Card><Card><p className="eyebrow">Commission earned</p><strong className="metric-value">{money(current.commission_amount_ngn)}</strong></Card><Card><p className="eyebrow">Pending</p><strong className="metric-value">{money(pending)}</strong></Card><Card><p className="eyebrow">Paid</p><strong className="metric-value">{money(paid)}</strong></Card></div>
    <Card><h2>Personal and HR information</h2><form action="/api/admin/growth-associates" method="post" className="form-grid"><input type="hidden" name="action" value="update_hr_profile"/><input type="hidden" name="id" value={p.id}/><input type="hidden" name="returnTo" value={`/admin/growth-associates/${p.id}`}/><label>Full name<input name="full_name" defaultValue={field(p.full_name)} required/></label><label>Phone / WhatsApp<input name="whatsapp" defaultValue={field(p.whatsapp)}/></label><label>Date of birth<input type="date" name="date_of_birth" defaultValue={field(p.date_of_birth)}/></label><label>Gender<input name="gender" defaultValue={field(p.gender)}/></label><label>Location<input name="location" defaultValue={field(p.location)}/></label><label>Institution<input name="institution" defaultValue={field(p.institution)}/></label><label>Course / field of study<input name="field_of_study" defaultValue={field(p.field_of_study)}/></label><label>Graduation information<input name="graduation_information" defaultValue={field(p.graduation_information)}/></label><label>NYSC information<input name="nysc_information" defaultValue={field(p.nysc_information)}/></label><label>Telegram username<input name="telegram_username" defaultValue={field(p.telegram_username)}/></label><label>Telegram user ID<input name="telegram_user_id" defaultValue={field(p.telegram_user_id)}/></label><label>Telegram chat ID<input name="telegram_chat_id" defaultValue={field(p.telegram_chat_id)}/></label><label>Interviewer<input name="interviewer" defaultValue={field(p.interviewer)}/></label><label>Interview notes<textarea name="interview_notes" defaultValue={field(p.interview_notes)}/></label><label>Inactive/rejection reason<textarea name="inactive_reason" defaultValue={field(p.inactive_reason)}/></label><button className="btn btn-primary">Save HR profile</button></form></Card>
    <Card><h2>Interview workflow</h2><p>Current status: <strong>{p.interview_status}</strong>{p.interview_date ? ` · ${new Date(p.interview_date).toLocaleString()}` : ''}</p><form action="/api/admin/growth-associates" method="post" className="form-grid"><input type="hidden" name="id" value={p.id}/><input type="hidden" name="returnTo" value={`/admin/growth-associates/${p.id}`}/><label>Interview date and time<input type="datetime-local" name="interview_date" defaultValue={p.interview_date ? new Date(p.interview_date).toISOString().slice(0,16) : ''}/></label><label>Interviewer<input name="interviewer" defaultValue={field(p.interviewer)}/></label><label>Interview notes<textarea name="interview_notes" defaultValue={field(p.interview_notes)}/></label><label>Decision reason<input name="reason" placeholder="Required when rejecting"/></label><div className="card-actions"><button className="btn btn-secondary" name="action" value="schedule_interview">Schedule interview</button><button className="btn btn-secondary" name="action" value="mark_interviewed">Mark interviewed</button><button className="btn btn-primary" name="action" value="pass_interview">Pass and activate</button><button className="btn btn-secondary" name="action" value="fail_interview">Fail / reject</button></div></form>{(interviewsResult.data || []).map((x: any) => <p key={x.id}><strong>{x.status}</strong> · {x.scheduled_at ? new Date(x.scheduled_at).toLocaleString() : 'No date'} · {x.interviewer || 'No interviewer'}<br/><span className="muted">{x.notes || x.outcome || 'No notes'}</span></p>)}</Card>
    <Card><h2>Level 2 hierarchy</h2><form action="/api/admin/growth-associates" method="post" className="card-actions"><input type="hidden" name="action" value="assign_sponsor"/><input type="hidden" name="id" value={p.id}/><input type="hidden" name="returnTo" value={`/admin/growth-associates/${p.id}`}/><select name="sponsorPartnerId" defaultValue={p.sponsor_partner_id || ''}><option value="">No sponsor</option>{(partnersResult.data || []).map((x: any) => <option value={x.id} key={x.id}>{x.full_name} ({x.partner_id})</option>)}</select><input name="reason" placeholder="Reason / note"/><button className="btn btn-primary">Save sponsor</button></form></Card>
    <Card><h2>Commission audit ledger</h2><div className="responsive-table"><table><thead><tr><th>Date</th><th>Referral type</th><th>Qualification</th><th>Amount</th><th>Status</th></tr></thead><tbody>{(commissionsResult.data || []).map((x: any) => <tr key={x.id}><td>{new Date(x.created_at).toLocaleDateString()}</td><td>Level {x.level}</td><td>{x.qualification_event || 'PAID_ENROLLMENT'}</td><td>{money(x.amount_ngn)}</td><td>{x.status}</td></tr>)}</tbody></table></div></Card>
    <Card><h2>Referral activity ({conversionsResult.data?.length || 0})</h2><div className="responsive-table"><table><thead><tr><th>Date</th><th>Payment</th><th>Course</th><th>Amount</th><th>Status</th><th>L1 commission</th></tr></thead><tbody>{(conversionsResult.data || []).map((x: any) => <tr key={x.id}><td>{new Date(x.successful_at).toLocaleDateString()}</td><td>{x.payments?.paystack_reference}</td><td>{x.payments?.payment_items?.map((y:any)=>y.programmes?.name).filter(Boolean).join(', ') || '—'}</td><td>{money(x.payments?.amount_ngn)}</td><td>{x.status}</td><td>{money(x.commission_amount_ngn)}</td></tr>)}</tbody></table></div></Card>
    <Card><h2>Payout history</h2>{(payoutsResult.data || []).length ? (payoutsResult.data || []).map((x: any) => <p key={x.id}>{x.created_at?.slice(0,10)} · {money(x.approved_amount_ngn || x.requested_amount_ngn)} · {x.status} · {x.reference || '—'}</p>) : <p>No payouts recorded.</p>}</Card>
  </div></AdminShell>
}
