import { redirect } from 'next/navigation'
import { AdminShell } from '@/components/shell'
import { Card } from '@/components/ui'
import { requireAdmin } from '@/lib/admin-auth'
import { audit, checked, classOptions, notifyClass, optional, trackOptions, value } from '@/lib/admin-learning'
import { createSupabaseAdminClient } from '@/lib/supabase/admin'

async function createProject(form:FormData){'use server';const admin=await requireAdmin(['SUPER_ADMIN','ADMIN','PROGRAMME_ADMIN']);const classId=value(form,'classId',50),published=checked(form,'published');const payload={title:value(form,'title',200),class_id:classId,track_id:optional(form,'trackId',50),cohort:optional(form,'cohort',100),description:optional(form,'description'),brief:optional(form,'instructions'),instructions:optional(form,'instructions'),deadline:optional(form,'deadline',40),external_url:optional(form,'externalUrl'),status:published?'PUBLISHED':'DRAFT',published,published_at:published?new Date().toISOString():null};if(!payload.title||!classId)return;const{data,error}=await createSupabaseAdminClient().from('projects').insert(payload).select('id').single();if(error)throw new Error(`Project creation failed: ${error.message}`);if(published)await notifyClass(classId,'project',data.id,payload.title,payload.description||'A new project is available.','/app/projects');await audit(admin,'PROJECT_CREATED','projects',data.id,payload);redirect(`/admin/projects/${data.id}`)}

export default async function NewProjectPage({searchParams}:{searchParams?:Promise<{classId?:string}>}){await requireAdmin(['SUPER_ADMIN','ADMIN','PROGRAMME_ADMIN']);const params=await searchParams;const[classes,tracks]=await Promise.all([classOptions(),trackOptions()]);return <AdminShell title="Create Project"><Card><form className="form-grid" action={createProject}><div className="grid-2"><label className="field"><span>Title</span><input name="title" required/></label><label className="field"><span>Class</span><select name="classId" defaultValue={params?.classId||''} required><option value="">Select class</option>{classes.map((x:any)=><option key={x.id} value={x.id}>{x.name||x.title} — {x.cohort||'No cohort'}</option>)}</select></label><label className="field"><span>Track</span><select name="trackId"><option value="">Class default</option>{tracks.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="field"><span>Deadline</span><input name="deadline" type="datetime-local"/></label><label className="field"><span>Description</span><textarea name="description"/></label><label className="field"><span>Instructions</span><textarea name="instructions"/></label><label className="field"><span>External project URL</span><input name="externalUrl" type="url"/></label><label className="inline-choice"><input name="published" type="checkbox"/> Publish and notify assigned class</label></div><button className="btn btn-primary">Create Project</button></form></Card></AdminShell>}
