import { notFound, redirect } from 'next/navigation'
import { AdminShell } from '@/components/shell'
import { Card } from '@/components/ui'
import { DataTable } from '@/components/product'
import { requireAdmin } from '@/lib/admin-auth'
import { audit, checked, optional, value } from '@/lib/admin-learning'
import { createSupabaseAdminClient } from '@/lib/supabase/admin'

async function save(form:FormData){'use server';const admin=await requireAdmin(['SUPER_ADMIN','ADMIN','PROGRAMME_ADMIN']);const id=value(form,'id',50);const payload={name:value(form,'name',180),slug:value(form,'slug',180),short_description:optional(form,'description'),price_ngn:Number(value(form,'price',20)||0),duration:optional(form,'duration',80),status:value(form,'status',30),active:checked(form,'active'),registration_open:checked(form,'registrationOpen')};const{error}=await createSupabaseAdminClient().from('programmes').update(payload).eq('id',id);if(error)throw new Error(`Programme update failed: ${error.message}`);await audit(admin,'PROGRAMME_UPDATED','programmes',id,payload);redirect('/admin/programmes')}
async function archive(form:FormData){'use server';const admin=await requireAdmin(['SUPER_ADMIN','ADMIN','PROGRAMME_ADMIN']);const id=value(form,'id',50),db=createSupabaseAdminClient();const[{count:enrolments},{count:payments},{count:tracks}]=await Promise.all([db.from('enrolments').select('id',{count:'exact',head:true}).eq('programme_id',id),db.from('payments').select('id',{count:'exact',head:true}).eq('programme_id',id),db.from('programme_tracks').select('id',{count:'exact',head:true}).eq('programme_id',id)]);const dependencies=(enrolments||0)+(payments||0)+(tracks||0);if(dependencies){await db.from('programmes').update({active:false,registration_open:false,status:'ARCHIVED',archived_at:new Date().toISOString()}).eq('id',id);await audit(admin,'PROGRAMME_ARCHIVED','programmes',id,{dependencies})}else{await db.from('programmes').delete().eq('id',id);await audit(admin,'PROGRAMME_DELETED','programmes',id)}redirect('/admin/programmes')}
export default async function ProgrammeDetail({params}:{params:Promise<{id:string}>}){await requireAdmin();const{id}=await params;const db=createSupabaseAdminClient();const[{data:p},{data:tracks},{count:enrolments},{count:payments}]=await Promise.all([db.from('programmes').select('*').eq('id',id).maybeSingle(),db.from('programme_tracks').select('*').eq('programme_id',id).order('name'),db.from('enrolments').select('id',{count:'exact',head:true}).eq('programme_id',id),db.from('payments').select('id',{count:'exact',head:true}).eq('programme_id',id)]);if(!p)notFound();return <AdminShell title="Edit Programme"><div className="page-grid"><Card><form className="form-grid" action={save}><input type="hidden" name="id" value={id}/><div className="grid-2"><label className="field"><span>Name</span><input name="name" defaultValue={p.name} required/></label><label className="field"><span>Slug</span><input name="slug" defaultValue={p.slug} required/></label><label className="field"><span>Description</span><textarea name="description" defaultValue={p.short_description||''}/></label><label className="field"><span>Price NGN</span><input name="price" type="number" defaultValue={p.price_ngn}/></label><label className="field"><span>Duration</span><input name="duration" defaultValue={p.duration||''}/></label><label className="field"><span>Status</span><select name="status" defaultValue={p.status}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><label className="inline-choice"><input name="active" type="checkbox" defaultChecked={p.active}/> Active</label><label className="inline-choice"><input name="registrationOpen" type="checkbox" defaultChecked={p.registration_open}/> Registration open</label></div><button className="btn btn-primary">Save Programme</button></form></Card><Card><h3>Tracks</h3><a className="btn btn-primary" href={`/admin/tracks/new?programmeId=${id}`}>Add Track</a><DataTable headers={['Track','Code','Status','Action']} rows={(tracks||[]).map((x:any)=>[x.name,x.track_code,x.active?'Active':'Inactive',`/admin/tracks/${x.id}`])}/></Card><Card><h3>Safe removal</h3><p className="muted">{enrolments||0} enrollments and {payments||0} payments depend on this programme. Historical dependencies cause archive/deactivation instead of destructive deletion.</p><form action={archive}><input type="hidden" name="id" value={id}/><button className="btn btn-secondary">{(enrolments||0)+(payments||0)+(tracks?.length||0)?'Archive Programme':'Delete Programme'}</button></form></Card></div></AdminShell>}
