import { notFound, redirect } from 'next/navigation'
import { AdminShell } from '@/components/shell'
import { Card } from '@/components/ui'
import { DataTable } from '@/components/product'
import { requireAdmin } from '@/lib/admin-auth'
import { audit, checked, classOptions, notifyClass, optional, value } from '@/lib/admin-learning'
import { createSupabaseAdminClient } from '@/lib/supabase/admin'

async function save(form:FormData){'use server';const admin=await requireAdmin(['SUPER_ADMIN','ADMIN','PROGRAMME_ADMIN']);const id=value(form,'id',50),classId=value(form,'classId',50),published=checked(form,'published');const payload={title:value(form,'title',200),class_id:classId,description:optional(form,'description'),instructions:optional(form,'instructions'),brief:optional(form,'instructions'),deadline:optional(form,'deadline',40),external_url:optional(form,'externalUrl'),status:published?'PUBLISHED':'DRAFT',published,published_at:published?new Date().toISOString():null};const{error}=await createSupabaseAdminClient().from('projects').update(payload).eq('id',id);if(error)throw new Error(`Project update failed: ${error.message}`);if(published)await notifyClass(classId,'project',id,payload.title,payload.description||'A project has been updated.','/app/projects');await audit(admin,'PROJECT_UPDATED','projects',id,payload);redirect('/admin/projects')}
async function archive(form:FormData){'use server';const admin=await requireAdmin(['SUPER_ADMIN','ADMIN','PROGRAMME_ADMIN']);const id=value(form,'id',50);await createSupabaseAdminClient().from('projects').update({archived_at:new Date().toISOString(),published:false,status:'ARCHIVED'}).eq('id',id);await audit(admin,'PROJECT_ARCHIVED','projects',id);redirect('/admin/projects')}
export default async function ProjectPage({params}:{params:Promise<{id:string}>}){await requireAdmin();const{id}=await params;const db=createSupabaseAdminClient();const[{data:project},{data:submissions},classes]=await Promise.all([db.from('projects').select('*').eq('id',id).maybeSingle(),db.from('project_submissions').select('*').eq('project_id',id),classOptions()]);if(!project)notFound();return <AdminShell title="Edit Project"><div className="page-grid"><Card><form className="form-grid" action={save}><input type="hidden" name="id" value={id}/><div className="grid-2"><label className="field"><span>Title</span><input name="title" defaultValue={project.title} required/></label><label className="field"><span>Class</span><select name="classId" defaultValue={project.class_id||''} required>{classes.map((x:any)=><option key={x.id} value={x.id}>{x.name||x.title}</option>)}</select></label><label className="field"><span>Description</span><textarea name="description" defaultValue={project.description||''}/></label><label className="field"><span>Instructions</span><textarea name="instructions" defaultValue={project.instructions||project.brief||''}/></label><label className="field"><span>Deadline</span><input name="deadline" type="datetime-local" defaultValue={project.deadline?.slice(0,16)||''}/></label><label className="field"><span>External URL</span><input name="externalUrl" type="url" defaultValue={project.external_url||''}/></label><label className="inline-choice"><input name="published" type="checkbox" defaultChecked={project.published}/> Published</label></div><button className="btn btn-primary">Save Project</button></form></Card><Card><h3>Submissions</h3><DataTable headers={['Learner','Status','Score','Submitted']} rows={(submissions||[]).map((x:any)=>[x.learner_id,x.status,String(x.score||'-'),x.submitted_at||'-'])}/></Card><Card><form action={archive}><input type="hidden" name="id" value={id}/><button className="btn btn-secondary">Archive Project</button></form></Card></div></AdminShell>}
