import Image from 'next/image'
import { ArrowRight, BriefcaseBusiness, GraduationCap, Menu } from 'lucide-react'
import { LandingLeadForm } from './landing-lead-form'
import { landingProgrammes } from '@/config/landing-programmes'
import './landing.css'

const audiences = [
  ['NYSC members & graduates', 'Turn emerging AI tools into practical career skills.'],
  ['Young professionals', 'Build confidence and produce stronger work.'],
  ['Working professionals', 'Apply AI to research, communication and everyday tasks.'],
  ['Executives', 'Lead thoughtful adoption across your team.'],
  ['Organizations', 'Equip people to work more effectively with AI.'],
]
const questions = [
  ['Who are the programs for?', 'Our learning paths are designed for students, NYSC members, graduates, working professionals and business teams.'],
  ['Do I need previous AI experience?', 'The current accelerator tracks welcome beginners. We will help you choose a starting point.'],
  ['How are courses delivered?', 'The current catalog describes instructor-led learning. Ask us about the next available class and format.'],
  ['How long does a program take?', 'Schedules vary by track and cohort. We will confirm dates and duration before you commit.'],
  ['Will I receive a certificate?', 'Certificate availability is confirmed for each cohort before enrolment. Ask our team about your chosen track.'],
  ['What does it cost?', 'The AI Accelerator is ₦10,000 per track. The Business Transformation Program is ₦25,000.'],
  ['Can my organization arrange training?', 'Yes. Tell us about your team and goals through the corporate training form.'],
]
function Action({ href, children, light = false }: { href: string; children: React.ReactNode; light?: boolean }) { return <a className={`institute-button ${light ? 'institute-button-light' : 'institute-button-dark'}`} href={href}>{children}<ArrowRight size={18} /></a> }

export default function InstituteHome({ interest, programme }: { interest?: string; programme?: string }) {
  return <div className="institute-site">
    <header className="institute-header"><a className="institute-brand" href="#top"><Image src="/nexora-mark.png" width={36} height={36} alt="" /><span>NEXORA <small>INSTITUTE</small></span></a><nav className="institute-desktop-nav" aria-label="Main navigation"><a href="#why">Why Nexora</a><a href="#programs">Programs</a><a href="#corporate">For organizations</a><a href="#community">Community</a></nav><a className="institute-header-cta" href="#interest">Get in touch <ArrowRight size={17} /></a><details className="institute-mobile-nav"><summary aria-label="Open menu"><Menu size={22} /></summary><nav aria-label="Mobile navigation"><a href="#why">Why Nexora</a><a href="#programs">Programs</a><a href="#corporate">For organizations</a><a href="#community">Community</a><a href="#interest">Get in touch</a></nav></details></header>
    <main id="top">
      <section className="institute-hero"><Image src="/nexora-workshop.png" alt="African professionals collaborating at a laptop" fill priority sizes="100vw" className="institute-hero-image" /><div className="institute-hero-shade" /><div className="institute-container institute-hero-content"><p className="institute-kicker">Nexora Institute</p><h1>BUILD YOUR<br />CAREER FOR<br />THE AI ERA.</h1><p>Practical AI skills for African careers, workplace productivity and business transformation.</p><div className="institute-actions"><Action href="#programs" light>Explore programs</Action><a className="institute-button institute-button-outline" href="/?interest=COMMUNITY#interest">Join the community</a></div></div></section>
      <section className="institute-band institute-intro" id="why"><div className="institute-container institute-two-column"><div><p className="institute-kicker">Why Nexora</p><h2>AI is changing how work gets done.</h2></div><div><p>Most people have heard about AI. Far fewer have had the chance to apply it to the decisions, projects and challenges they face at work.</p><p>Nexora Institute focuses on useful capability: learning with purpose, practising on real tasks and knowing where AI belongs in your workflow.</p></div></div></section>
      <section className="institute-band institute-audiences" id="audiences"><div className="institute-container"><p className="institute-kicker">Who we serve</p><h2>Built for the people shaping what comes next.</h2><div className="institute-audience-list">{audiences.map(([name, detail], index) => <div key={name}><span>0{index + 1}</span><h3>{name}</h3><p>{detail}</p></div>)}</div></div></section>
      <section className="institute-band institute-programs" id="programs"><div className="institute-container"><p className="institute-kicker">Programs</p><h2>Choose a practical path.</h2><p className="institute-section-lead">Focused learning for personal growth and better work.</p><div className="institute-program-list">{landingProgrammes.map((item) => <article className="institute-program" key={item.code}><div><span className="institute-program-icon">{item.code === 'AI_ACCELERATOR' ? <GraduationCap size={24} /> : <BriefcaseBusiness size={24} />}</span><h3>{item.name}</h3><p className="institute-program-audience">{item.audience}</p><p>{item.problem} {item.outcome}</p></div><div className="institute-program-bottom"><div>{item.tracks.length ? <><strong>Current tracks</strong><ul>{item.tracks.map((track) => <li key={track.code}>{track.name}</li>)}</ul></> : <p>Tell us about your business goals and our team will guide you.</p>}</div><div className="institute-program-action"><strong>{item.priceNgn ? `₦${item.priceNgn.toLocaleString('en-NG')} ${item.priceUnit}` : 'Price on enquiry'}</strong><a href={`/?interest=PROGRAM_INTEREST&programme=${item.code}#interest`}>Enquire <ArrowRight size={17} /></a></div></div></article>)}</div></div></section>
      <section className="institute-band institute-corporate" id="corporate"><div className="institute-container institute-two-column"><div><p className="institute-kicker">For organizations</p><h2>PREPARE YOUR TEAM FOR THE AI ERA.</h2></div><div><p>We help teams develop practical AI capability for the work they already do. Training can focus on productivity, communication, research, reporting, workflow improvement and responsible adoption.</p><Action href="/?interest=CORPORATE_TRAINING#interest" light>Request corporate training</Action></div></div></section>
      <section className="institute-band institute-opportunities"><div className="institute-container institute-two-column"><div><p className="institute-kicker">Ambassador program</p><h2>Help more people find their next opportunity.</h2></div><div><p>NYSC corps members and eligible university students can express interest in representing Nexora and connecting their communities with practical learning.</p><a className="institute-text-link" href="/?interest=AMBASSADOR#interest">Become an ambassador <ArrowRight size={18} /></a></div></div></section>
      <section className="institute-band institute-community" id="community"><div className="institute-container institute-two-column"><div><p className="institute-kicker">Community</p><h2>DON'T LEARN AI ALONE.</h2></div><div><p>Find people learning to apply AI with intention. Join the Nexora community for conversation, shared progress and updates on upcoming learning opportunities.</p><Action href="/?interest=COMMUNITY#interest">Join the Nexora community</Action></div></div></section>
      <section className="institute-band institute-faq" id="faq"><div className="institute-container institute-two-column"><div><p className="institute-kicker">Questions</p><h2>Good to know before you begin.</h2></div><div className="institute-faq-list">{questions.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section>
      <section className="institute-band institute-interest" id="interest"><div className="institute-container institute-two-column"><div><p className="institute-kicker">Your next step</p><h2>Start building practical AI capability.</h2><p>Tell us what you are looking for. We will help you find the right path.</p></div><LandingLeadForm initialType={interest} initialProgramme={programme} /></div></section>
    </main>
    <footer className="institute-footer"><div className="institute-container"><div className="institute-footer-top"><div><a className="institute-brand" href="#top"><Image src="/nexora-mark.png" width={32} height={32} alt="" /><span>NEXORA <small>INSTITUTE</small></span></a><p>Building Africa's AI-ready workforce.</p></div><a href="mailto:admin@nexoragroup.ink">admin@nexoragroup.ink</a></div><div className="institute-footer-bottom"><span>© {new Date().getFullYear()} Nexora Institute</span><a href="#top">Back to top ↑</a></div></div></footer>
  </div>
}
