import { notFound } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import { AdminShell } from '@/components/shell'
import { Card } from '@/components/ui'
import { DataTable, MetricCard } from '@/components/product'
import { requireAdmin } from '@/lib/admin-auth'
import { audit, checked, notifyClass, optional, value } from '@/lib/admin-learning'
import { createSupabaseAdminClient } from '@/lib/supabase/admin'

async function addStudent(form: FormData) {
  'use server'
  const admin = await requireAdmin(['SUPER_ADMIN','ADMIN','PROGRAMME_ADMIN'])
  const classId=value(form,'classId',50), enrolmentId=value(form,'enrolmentId',50)
  const db=createSupabaseAdminClient()
  const {data:enrolment}=await db.from('enrolments').select('id,user_id').eq('id',enrolmentId).single()
  if(!enrolment?.user_id) throw new Error('Select a valid enrolled student.')
  const {error}=await db.from('class_memberships').upsert({class_id:classId,user_id:enrolment.user_id,enrolment_id:enrolment.id,status:'ACTIVE',removed_at:null},{onConflict:'class_id,user_id'})
  if(error) throw new Error(`Adding student failed: ${error.message}`)
  await audit(admin,'CLASS_STUDENT_ADDED','class_memberships',enrolment.user_id,{classId})
  revalidatePath(`/admin/classes/${classId}`)
}

async function removeStudent(form: FormData) {
  'use server'
  const admin=await requireAdmin(['SUPER_ADMIN','ADMIN','PROGRAMME_ADMIN'])
  const classId=value(form,'classId',50), membershipId=value(form,'membershipId',50)
  const {error}=await createSupabaseAdminClient().from('class_memberships').update({status:'REMOVED',removed_at:new Date().toISOString()}).eq('id',membershipId).eq('class_id',classId)
  if(error) throw new Error(`Removing student failed: ${error.message}`)
  await audit(admin,'CLASS_STUDENT_REMOVED','class_memberships',membershipId,{classId})
  revalidatePath(`/admin/classes/${classId}`)
}

async function createContent(form: FormData) {
  'use server'
  const admin=await requireAdmin(['SUPER_ADMIN','ADMIN','PROGRAMME_ADMIN'])
  const db=createSupabaseAdminClient(), classId=value(form,'classId',50), kind=value(form,'kind',30), published=checked(form,'published')
  let table='', payload:Record<string,unknown>={class_id:classId,title:value(form,'title',200),published,published_at:published?new Date().toISOString():null}
  if(kind==='session'){table='live_sessions';payload={...payload,description:optional(form,'description'),session_date:value(form,'date',20),start_time:optional(form,'startTime',20),end_time:optional(form,'endTime',20),trainer:optional(form,'trainer',160),meeting_platform:optional(form,'platform',80),meeting_url:optional(form,'url'),meeting_id:optional(form,'meetingId',100),meeting_password:optional(form,'meetingPassword',100),status:published?'PUBLISHED':'DRAFT'}}
  else if(kind==='assignment'){table='assignments';payload={...payload,description:optional(form,'description'),instructions:optional(form,'instructions'),due_at:optional(form,'dueAt',40),external_submission_url:optional(form,'url'),status:published?'PUBLISHED':'DRAFT'}}
  else if(kind==='resource'){table='learning_resources';let storagePath=optional(form,'storagePath');const file=form.get('file');if(file instanceof File&&file.size){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-').slice(-140);storagePath=`${classId}/${crypto.randomUUID()}-${safe}`;const{error:uploadError}=await db.storage.from('class-content').upload(storagePath,file,{contentType:file.type||'application/octet-stream',upsert:false});if(uploadError)throw new Error(`Resource upload failed: ${uploadError.message}`)}payload={...payload,description:optional(form,'description'),resource_type:value(form,'resourceType',30)||'LINK',external_url:optional(form,'url'),storage_path:storagePath,session_label:optional(form,'sessionLabel',100)}}
  else if(kind==='announcement'){table='announcements';payload={...payload,body:value(form,'description',5000)}}
  else throw new Error('Unsupported class content type.')
  const {data,error}=await db.from(table).insert(payload).select('id').single()
  if(error) throw new Error(`${kind} creation failed: ${error.message}`)
  if(published) await notifyClass(classId,kind,data.id,String(payload.title),kind==='announcement'?String(payload.body):String(payload.description||`A new ${kind} is available.`),kind==='session'?'/app/classes':kind==='resource'?'/app/resources':'/app/projects')
  await audit(admin,`${kind.toUpperCase()}_CREATED`,table,data.id,payload)
  revalidatePath(`/admin/classes/${classId}`)
}

async function archiveClass(form:FormData){'use server';const admin=await requireAdmin(['SUPER_ADMIN','ADMIN','PROGRAMME_ADMIN']);const id=value(form,'classId',50);await createSupabaseAdminClient().from('classes').update({archived_at:new Date().toISOString(),status:'ARCHIVED'}).eq('id',id);await audit(admin,'CLASS_ARCHIVED','classes',id);revalidatePath(`/admin/classes/${id}`)}
async function saveClass(form:FormData){'use server';const admin=await requireAdmin(['SUPER_ADMIN','ADMIN','PROGRAMME_ADMIN']);const id=value(form,'classId',50),payload={name:value(form,'name',180),title:value(form,'name',180),cohort:optional(form,'cohort',120),trainer:optional(form,'trainer',160),starts_at:optional(form,'startsAt',20),ends_at:optional(form,'endsAt',20),status:value(form,'status',30)};const{error}=await createSupabaseAdminClient().from('classes').update(payload).eq('id',id);if(error)throw new Error(`Class update failed: ${error.message}`);await audit(admin,'CLASS_UPDATED','classes',id,payload);revalidatePath(`/admin/classes/${id}`)}
async function manageContent(form:FormData){'use server';const admin=await requireAdmin(['SUPER_ADMIN','ADMIN','PROGRAMME_ADMIN']);const classId=value(form,'classId',50),id=value(form,'id',50),table=value(form,'table',40),operation=value(form,'operation',20);if(!['live_sessions','assignments','learning_resources','announcements'].includes(table))throw new Error('Unsupported content type.');const db=createSupabaseAdminClient();const{data:item}=await db.from(table).select('*').eq('id',id).eq('class_id',classId).single();if(!item)throw new Error('Class content was not found.');const update=operation==='archive'?(table==='live_sessions'?{published:false,status:'ARCHIVED'}:{published:false,archived_at:new Date().toISOString()}):{published:!item.published,published_at:!item.published?new Date().toISOString():null};const{error}=await db.from(table).update(update).eq('id',id).eq('class_id',classId);if(error)throw new Error(`Content update failed: ${error.message}`);if(operation!=='archive'&&!item.published)await notifyClass(classId,table,id,item.title,item.description||item.body||'New class content is available.',table==='live_sessions'?'/app/classes':table==='learning_resources'?'/app/resources':'/app/projects');await audit(admin,'CLASS_CONTENT_UPDATED',table,id,update);revalidatePath(`/admin/classes/${classId}`)}

export default async function ClassDetailPage({params}:{params:Promise<{id:string}>}){
  await requireAdmin();const {id}=await params;const db=createSupabaseAdminClient()
  const [{data:group},{data:members},{data:eligible},{data:sessions},{data:assignments},{data:projects},{data:resources},{data:announcements}]=await Promise.all([
    db.from('classes').select('*,programmes(name),programme_tracks(name)').eq('id',id).maybeSingle(),
    db.from('class_memberships').select('id,status,joined_at,enrolments(status,created_at,programme_tracks(name),profiles(id,full_name,email),payments(status))').eq('class_id',id).eq('status','ACTIVE').order('joined_at'),
    db.from('enrolments').select('id,status,profiles(id,full_name,email)').eq('programme_id',(await db.from('classes').select('programme_id').eq('id',id).single()).data?.programme_id).limit(300),
    db.from('live_sessions').select('*').eq('class_id',id).order('session_date'),db.from('assignments').select('*').eq('class_id',id).order('created_at',{ascending:false}),db.from('projects').select('*').eq('class_id',id).order('created_at',{ascending:false}),db.from('learning_resources').select('*').eq('class_id',id).order('created_at',{ascending:false}),db.from('announcements').select('*').eq('class_id',id).order('created_at',{ascending:false})])
  if(!group) notFound()
  return <AdminShell title={group.name||group.title}><div className="page-grid">
    <div className="metric-grid"><MetricCard label="Students" value={String(members?.length||0)} note="Explicit active memberships"/><MetricCard label="Programme" value={(group.programmes as any)?.name||'-'} note={(group.programme_tracks as any)?.name||'All tracks'}/><MetricCard label="Cohort" value={group.cohort||'-'} note={`${group.starts_at||'-'} — ${group.ends_at||'-'}`}/><MetricCard label="Status" value={group.status} note={group.trainer||'Trainer not assigned'}/></div>
    <div className="tabs"><a href="#overview">Overview</a><a href="#students">Students</a><a href="#sessions">Live Classes</a><a href="#assignments">Assignments</a><a href="#projects">Projects</a><a href="#resources">Resources & Recordings</a><a href="#announcements">Announcements</a></div>
    <Card><h3 id="overview">Class Overview</h3><form className="form-grid" action={saveClass}><input type="hidden" name="classId" value={id}/><div className="grid-2"><label className="field"><span>Name</span><input name="name" defaultValue={group.name||group.title}/></label><label className="field"><span>Cohort</span><input name="cohort" defaultValue={group.cohort||''}/></label><label className="field"><span>Trainer</span><input name="trainer" defaultValue={group.trainer||''}/></label><label className="field"><span>Start</span><input name="startsAt" type="date" defaultValue={group.starts_at||''}/></label><label className="field"><span>End</span><input name="endsAt" type="date" defaultValue={group.ends_at||''}/></label><label className="field"><span>Status</span><select name="status" defaultValue={group.status}><option>DRAFT</option><option>ACTIVE</option><option>COMPLETED</option><option>ARCHIVED</option></select></label></div><button className="btn btn-primary">Save Class</button></form></Card>
    <Card><h3 id="students">Students</h3><form className="card-actions" action={addStudent}><input type="hidden" name="classId" value={id}/><select name="enrolmentId" required><option value="">Add enrolled student</option>{(eligible||[]).map((e:any)=><option key={e.id} value={e.id}>{e.profiles?.full_name||e.profiles?.email||e.id} — {e.status}</option>)}</select><button className="btn btn-primary">Add Student</button></form><DataTable headers={['Student','Email','Enrollment','Track','Payment','Joined']} rows={(members||[]).map((m:any)=>[m.enrolments?.profiles?.full_name||'-',m.enrolments?.profiles?.email||'-',m.enrolments?.status||'-',m.enrolments?.programme_tracks?.name||'-',m.enrolments?.payments?.[0]?.status||'-',new Date(m.joined_at).toLocaleDateString()])}/>{(members||[]).map((m:any)=><form key={m.id} action={removeStudent} className="card-actions"><input type="hidden" name="classId" value={id}/><input type="hidden" name="membershipId" value={m.id}/><span>{m.enrolments?.profiles?.email}</span><button className="btn btn-ghost">Remove</button></form>)}</Card>
    <ContentForm id="sessions" title="Live Classes" kind="session" classId={id}/><DataTable headers={['Session','Date','Time','Trainer','Published']} rows={(sessions||[]).map((x:any)=>[x.title,x.session_date,`${x.start_time||'-'} – ${x.end_time||'-'}`,x.trainer||'-',x.published?'Published':'Draft'])}/><ManageRows items={sessions||[]} table="live_sessions" classId={id}/>
    <ContentForm id="assignments" title="Assignments" kind="assignment" classId={id}/><DataTable headers={['Assignment','Due','Status','Published']} rows={(assignments||[]).map((x:any)=>[x.title,x.due_at||'-',x.status,x.published?'Published':'Draft'])}/><ManageRows items={assignments||[]} table="assignments" classId={id}/>
    <Card><h3 id="projects">Projects</h3><a className="btn btn-primary" href={`/admin/projects/new?classId=${id}`}>Create Project for Class</a><DataTable headers={['Project','Deadline','Status','Published','Action']} rows={(projects||[]).map((x:any)=>[x.title,x.deadline||'-',x.status,x.published?'Published':'Draft',`/admin/projects/${x.id}`])}/></Card>
    <ContentForm id="resources" title="Resources & Recorded Classes" kind="resource" classId={id}/><DataTable headers={['Resource','Type','Session','Published']} rows={(resources||[]).map((x:any)=>[x.title,x.resource_type,x.session_label||'-',x.published?'Published':'Draft'])}/><ManageRows items={resources||[]} table="learning_resources" classId={id}/>
    <ContentForm id="announcements" title="Announcements" kind="announcement" classId={id}/><DataTable headers={['Announcement','Published','Created']} rows={(announcements||[]).map((x:any)=>[x.title,x.published?'Published':'Draft',new Date(x.created_at).toLocaleDateString()])}/><ManageRows items={announcements||[]} table="announcements" classId={id}/><Card><h3>Quizzes & Assessments</h3><p className="muted">Create database-backed questions for this class.</p><a className="btn btn-primary" href={`/admin/classes/${id}/assessments/new`}>Create Assessment</a></Card>
    <Card><h3>Class lifecycle</h3><form action={archiveClass}><input type="hidden" name="classId" value={id}/><button className="btn btn-secondary">Archive Class</button></form></Card>
  </div></AdminShell>
}

function ContentForm({id,title,kind,classId}:{id:string;title:string;kind:string;classId:string}){return <Card><h3 id={id}>{title}</h3><form className="form-grid" action={createContent}><input type="hidden" name="classId" value={classId}/><input type="hidden" name="kind" value={kind}/><div className="grid-2"><label className="field"><span>Title</span><input name="title" required/></label><label className="field"><span>Description / instructions</span><textarea name="description"/></label>{kind==='session'?<><label className="field"><span>Date</span><input name="date" type="date" required/></label><label className="field"><span>Start time</span><input name="startTime" type="time"/></label><label className="field"><span>End time</span><input name="endTime" type="time"/></label><label className="field"><span>Trainer</span><input name="trainer"/></label><label className="field"><span>Meeting platform</span><input name="platform"/></label><label className="field"><span>Meeting URL</span><input name="url" type="url"/></label></>:null}{kind==='assignment'?<><label className="field"><span>Instructions</span><textarea name="instructions"/></label><label className="field"><span>Due</span><input name="dueAt" type="datetime-local"/></label><label className="field"><span>Submission URL</span><input name="url" type="url"/></label></>:null}{kind==='resource'?<><label className="field"><span>Type</span><select name="resourceType"><option>LINK</option><option>PDF</option><option>DOCUMENT</option><option>IMAGE</option><option>VIDEO</option><option>TEMPLATE</option></select></label><label className="field"><span>Upload private file</span><input name="file" type="file"/></label><label className="field"><span>External URL</span><input name="url" type="url"/></label><label className="field"><span>Existing private storage path</span><input name="storagePath" placeholder={`${classId}/recording.mp4`}/></label><label className="field"><span>Session/week</span><input name="sessionLabel"/></label></>:null}<label className="inline-choice"><input type="checkbox" name="published"/> Publish now and notify class</label></div><button className="btn btn-primary">Create {title}</button></form></Card>}
function ManageRows({items,table,classId}:{items:any[];table:string;classId:string}){return <Card><h3>Publish & Archive</h3>{items.map((x:any)=><form key={x.id} action={manageContent} className="card-actions"><input type="hidden" name="classId" value={classId}/><input type="hidden" name="id" value={x.id}/><input type="hidden" name="table" value={table}/><strong>{x.title}</strong><button className="btn btn-ghost" name="operation" value="toggle">{x.published?'Unpublish':'Publish'}</button><button className="btn btn-secondary" name="operation" value="archive">Archive</button></form>)}</Card>}
