'use client'
import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Card } from '@/components/ui'
type Bank = { name: string; code: string }
export default function GrowthRegisterPage() {
  const router = useRouter(); const [banks,setBanks]=useState<Bank[]>([]); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false)
  useEffect(()=>{ fetch('/api/paystack/banks').then(r=>r.json()).then(b=>setBanks(b.banks||[])).catch(()=>setMessage('Banks could not be loaded. Please refresh.')) },[])
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('Creating your account…');const payload=Object.fromEntries(new FormData(event.currentTarget).entries());const response=await fetch('/api/growth/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const body=await response.json().catch(()=>({}));if(!response.ok){setMessage(body.message||'Registration failed. Please try again.');setBusy(false);return}setMessage(`Account created. Your Growth ID is ${body.growthId}.`);router.replace('/growth/portal');router.refresh()}
  return <main className="associate-login"><Card><Link className="brand" href="/">Nexora Institute</Link><p className="eyebrow">Growth Associate</p><h1>Create your account</h1><p className="muted">Register, receive your permanent Growth ID, and start sharing your referral link.</p><form className="form-grid" onSubmit={submit}><label className="field"><span>Full Name</span><input name="fullName" required autoComplete="name"/></label><label className="field"><span>WhatsApp Number</span><input name="whatsapp" required inputMode="tel" autoComplete="tel" placeholder="08012345678"/></label><label className="field"><span>Account Name</span><input name="accountName" required/></label><label className="field"><span>Bank Name</span><select name="bankCode" required defaultValue=""><option value="" disabled>Select your bank</option>{banks.map(bank=><option key={bank.code} value={bank.code}>{bank.name}</option>)}</select></label><label className="field"><span>Account Number</span><input name="accountNumber" required inputMode="numeric" pattern="[0-9]{10}" maxLength={10}/></label><label className="field"><span>Password</span><input name="password" type="password" required minLength={8} autoComplete="new-password"/></label><label className="field"><span>Confirm Password</span><input name="confirmPassword" type="password" required minLength={8} autoComplete="new-password"/></label>{message?<p className="form-message" aria-live="polite">{message}</p>:null}<button className="btn btn-primary" disabled={busy}>{busy?'Creating account…':'Create Growth Associate account'}</button></form><p>Already registered? <Link href="/growth/login">Sign in</Link></p></Card></main>
}
